apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend2
  labels:
    app: sa-frontend
spec:
  containers:
    - image: eqmvii/k8stutorial-nginx-frontend:1
      name: sa-frontend
      ports:
        - containerPort: 80
